<?php
/* Planetoid configuration file */
/* Generated by Planetoid on Mon, 09 Apr 2007 16:57:17 +0200 */

define('SQL_TYPE', 'pgsql'); /* mysql or pgsql */
define('SQL_USER', 'josip'); /* username */
define('SQL_PASS', 'pass'); /* passowrd */
define('SQL_DB_NAME', 'planetoid'); /* DB name */
define('SQL_HOST', 'localhost'); /* host */
define('SQL_PORT', 5432); /* pgsql port */
?>
