<?php

header("Content-Type: text/xml");

include_once('inc/simplepie/idn/idna_convert.class.php');
include_once('inc/simplepie/simplepie.inc');
include('config.php');
include('planetoid.php');

$feeds_list= list_feeds();

// echo "<!-- <ownerName> <?php $name_mail= sql_action("SELECT name, email FROM users WHERE role_level='admin'"); echo $name['name']; ?\></ownerName><ownerEmail><?php echo $name_mail['email']; ?\><ownerEmail> -->"
?>

<!-- Generated by Planetoid <?php echo PLANETOID_VERSION; ?> -->
<opml version="1.0">
	<head>
		<title>Blogs aggregated on <?php echo get_title(); ?></title>
		<dateCreated><?php echo date('r'); ?></dateCreated>
	</head>
	<body>
<?php
for($n= 0; $n < count($feeds_list); $n++) {
	$feed= $feeds_list[$n];
	$title= $feed['title'];
	$url= $feed['feedUrl'];
	$type= $feed['type'];
	echo "\t\t\t<outline text=\"$title\" title=\"$title\" xmlUrl=\"".str_replace('&', '&amp;', $url)."\" type=\"$type\"/>\n";
};

sql_close();
?>
	</body>
</opml>