<?php
header("Content-Type: text/xml");

require_once('inc/simplepie/idn/idna_convert.class.php');
require_once('inc/simplepie/simplepie.inc');
require_once('config.php');
require_once('planetoid.php');

$feeds_list= list_feeds();
?>
<!-- Generated by Planetoid <?=PLANETOID_VERSION?>.<?=PLANETOID_REVISION?> -->
<opml version="1.0">
	<head>
		<title>Blogs aggregated on <?=get_title()?></title>
		<dateCreated><?=last_refresh()?></dateCreated>
	</head>
	<body>
<?php
for($n= 0; $n < count($feeds_list); $n++):
	$feed= $feeds_list[$n];
	?>
	<outline
		text="<?=$feed['title']?>"
		title="<?=$feed['title']?>"
		xmlUrl="<?=$feed['feedUrl']?>"
		type="<?=$feed['type']?>" />
<?php endfor; sql_close(); ?>
	</body>
</opml>
