<?php

header("Content-Type: text/xml");

include_once('inc/simplepie/idn/idna_convert.class.php');
include_once('inc/simplepie/simplepie.inc');
include('config.php');
include('planetoid.php');

$feeds_list= list_feeds();
?>
<!-- Generated by Planetoid <?=PLANETOID_VERSION?> -->
<opml version="1.0">
	<head>
		<title>Blogs aggregated on <?=get_title()?></title>
		<dateCreated><?=date('r')?></dateCreated>
	</head>
	<body>
<?php
for($n= 0; $n < count($feeds_list); $n++):
	$feed= $feeds_list[$n];
	?>
	<outline
		text="<?=$feed['title']?>"
		title="<?$feed['title']?>"
		xmlUrl="<?=str_replace('&', '&amp;', $feed['url'])?>"
		type="<?=$feed['type']?>" />
<?php endfor;sql_close(); ?>
	</body>
</opml>
